// <auto-generated />
using Assignment_10._3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_10._3.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_10._3.Models.Car", b =>
                {
                    b.Property<int>("VIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VIN"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VIN");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            VIN = 1234,
                            Make = "Toyota",
                            Model = "Prius",
                            Price = 20000.0,
                            Year = 2020
                        },
                        new
                        {
                            VIN = 2345,
                            Make = "Honda",
                            Model = "Civic",
                            Price = 25000.0,
                            Year = 2023
                        },
                        new
                        {
                            VIN = 3456,
                            Make = "Tesla",
                            Model = "Cyber Truck",
                            Price = 50000.0,
                            Year = 2024
                        },
                        new
                        {
                            VIN = 4567,
                            Make = "Hyundai",
                            Model = "Ioniq",
                            Price = 40000.0,
                            Year = 2026
                        },
                        new
                        {
                            VIN = 5678,
                            Make = "Ford",
                            Model = "F150",
                            Price = 40000.0,
                            Year = 2026
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
